import DesignTokens from "../DesignTokens";

const typography = {
  htmlFontSize: 16,
  fontFamily: '"Nunito Sans", "Helvetica", "Arial", sans-serif',
  fontSize: 14,
  fontWeightLight: 300,
  fontWeightRegular: 400,
  fontWeightMedium: 500,
  fontWeightBold: 700,
  h1: {
    fontFamily: '"Nunito Sans", "Helvetica", "Arial", sans-serif',
    fontWeight: 700,
    fontSize: "2rem",
    lineHeight: 1.375,
    letterSpacing: "0em",
  },
  h2: {
    fontFamily: '"Nunito Sans", "Helvetica", "Arial", sans-serif',
    fontWeight: 700,
    fontSize: "1.75rem",
    lineHeight: 1.429,
    letterSpacing: "0em",
  },
  h3: {
    fontFamily: '"Nunito Sans", "Helvetica", "Arial", sans-serif',
    fontWeight: 700,
    fontSize: "1.5rem",
    lineHeight: 1.5,
    letterSpacing: "0em",
  },
  h4: {
    fontFamily: '"Nunito Sans", "Helvetica", "Arial", sans-serif',
    fontWeight: 700,
    fontSize: "1.25rem",
    lineHeight: 2.0,
    letterSpacing: "0.00735em",
  },
  h5: {
    fontFamily: '"Nunito Sans", "Helvetica", "Arial", sans-serif',
    fontWeight: 400,
    fontSize: "1.25rem",
    lineHeight: 2.0,
    letterSpacing: "0em",
  },
  h6: {
    fontFamily: '"Nunito Sans", "Helvetica", "Arial", sans-serif',
    fontWeight: 800,
    fontSize: "1rem",
    lineHeight: 1.25,
    letterSpacing: "0em",
  },
  subtitle1: {
    fontFamily: '"Nunito Sans", "Helvetica", "Arial", sans-serif',
    fontWeight: 400,
    fontSize: "1rem",
    lineHeight: 1.5,
    letterSpacing: "0em",
  },
  subtitle2: {
    fontFamily: '"Nunito Sans", "Helvetica", "Arial", sans-serif',
    fontWeight: 600,
    fontSize: "0.875rem",
    lineHeight: 1.5,
    letterSpacing: "0em",
  },
  body1: {
    fontFamily: '"Nunito Sans", "Helvetica", "Arial", sans-serif',
    fontWeight: 400,
    fontSize: "0.875rem",
    lineHeight: 1.5,
    letterSpacing: "0em",
  },
  body2: {
    fontFamily: '"Nunito Sans", "Helvetica", "Arial", sans-serif',
    fontWeight: 400,
    fontSize: "0.75rem",
    lineHeight: 1,
    letterSpacing: "0em",
  },
  button: {
    fontFamily: '"Nunito Sans", "Helvetica", "Arial", sans-serif',
    fontWeight: 600,
    fontSize: "0.875rem",
    lineHeight: 1.75,
    letterSpacing: "0em",
    textTransform: "none",
  },
  caption: {
    fontFamily: '"Nunito Sans", "Helvetica", "Arial", sans-serif',
    fontWeight: 600,
    fontSize: "0.75rem",
    lineHeight: 1,
    letterSpacing: "0.03333em",
  },
  overline: {
    fontFamily: '"Nunito Sans", "Helvetica", "Arial", sans-serif',
    fontWeight: 400,
    fontSize: "0.75rem",
    lineHeight: 2.66,
    letterSpacing: "0.08333em",
    textTransform: "uppercase",
  },
  inherit: {
    fontFamily: "inherit",
    fontWeight: "inherit",
    fontSize: "inherit",
    lineHeight: "inherit",
    letterSpacing: "inherit",
  },
};

export default typography;
